import { NextRequest, NextResponse } from "next/server";
import { HISTORICAL_SCENARIOS, runHistoricalStressRange, runMacroStress, type HistoricalScenarioId } from "@/lib/macroStress/engine";
import type { MacroStressResponse, Vector, Weights } from "@/lib/macroStress/types";
export const runtime="nodejs"; export const dynamic="force-dynamic";
export const maxDuration=60;
const DAY=86_400_000,cache=new Map<string,{at:number;value:Promise<MacroStressResponse>}>();
function weightsFrom(request:NextRequest):Weights {const query=request.nextUrl.searchParams,raw={sp500:Number(query.get("us")??.4),kospi:Number(query.get("kr")??.3),treasury:Number(query.get("bond")??.3)},total=Object.values(raw).reduce((sum,value)=>sum+(Number.isFinite(value)&&value>=0?value:0),0);if(total<=0)throw new Error("Weights must be non-negative.");return {sp500:raw.sp500/total,kospi:raw.kospi/total,treasury:raw.treasury/total};}
function scenarioFrom(request:NextRequest):{id:HistoricalScenarioId|"custom";center?:Vector}{const query=request.nextUrl.searchParams,id=query.get("scenario")??"custom";if(id!=="custom"){if(!(id in HISTORICAL_SCENARIOS))throw new Error("Unknown historical scenario.");return {id:id as HistoricalScenarioId};}const center={d_fed:Number(query.get("d_fed")),d_ust:Number(query.get("d_ust")),ret_krw:Number(query.get("ret_krw")),infl:Number(query.get("infl")),ret_cmd:Number(query.get("ret_cmd")),d_vix:Number(query.get("d_vix"))};if(!Object.values(center).every(Number.isFinite))throw new Error("Custom scenario requires six numeric factors.");return {id:"custom",center};}
export async function GET(request:NextRequest){try{const weights=weightsFrom(request);if(request.nextUrl.searchParams.get("summary")==="range")return NextResponse.json(await runHistoricalStressRange(weights),{headers:{"Cache-Control":"public, s-maxage=86400, stale-while-revalidate=3600"}});const scenario=scenarioFrom(request),key=request.nextUrl.searchParams.toString(),hit=cache.get(key);let value:Promise<MacroStressResponse>,cacheStatus="HIT";if(hit&&Date.now()-hit.at<DAY)value=hit.value;else{cacheStatus="MISS";value=runMacroStress(weights,scenario.id,scenario.center,50_000).catch(error=>{cache.delete(key);throw error;});cache.set(key,{at:Date.now(),value});if(cache.size>20)cache.delete(cache.keys().next().value!);}return NextResponse.json(await value,{headers:{"Cache-Control":"public, s-maxage=86400, stale-while-revalidate=3600","X-Macro-Stress-Cache":cacheStatus}});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Macro stress calculation failed"},{status:500});}}
