"use client";

import { useEffect, useState } from "react";
import { themeLabelKo } from "@/lib/topPicks/themeLabels";

type Pick = { rank: number; previousRank: number | null; rankChange: number | null; isNew: boolean; ticker: string; company: string; score: number; confidence: number; type: string; summary: string; keyReasons: string[]; risks: string[]; scores: Record<string, number> };
type HomeData = { demo?: boolean; ready: boolean; date: string | null; marketBrief: null | { headline: string; summary: string; indicators: Array<{ label?: string; value?: string; change?: string }>; issues: Array<{ title?: string; summary?: string; whatChanged?: string; marketImpact?: string; watchPoint?: string }>; themes: Array<{ theme?: string; themeCode?: string; themeKo?: string; score?: number; direction?: string; reason?: string }>; timeline?: { twoWeeks?: string; threeDays?: string; today?: string }; watchPoints?: string[] }; topPicks: Pick[] };

const scoreLabels: Record<string, string> = { research: "Research", fundamental: "Fundamental", price: "Price", consensus: "Consensus", regime: "Regime" };
const typeTone: Record<string, string> = { CORE: "bg-blue-50 text-blue-700", GROWTH: "bg-violet-50 text-violet-700", MOMENTUM: "bg-emerald-50 text-emerald-700", DEFENSIVE: "bg-amber-50 text-amber-700" };

function RankChange({ pick }: { pick: Pick }) {
  if (pick.isNew) return <span className="text-[11px] font-bold text-[#1769D2]">NEW</span>;
  if (!pick.rankChange) return <span className="text-[11px] text-fg-muted">—</span>;
  return <span className={`text-[11px] font-bold ${pick.rankChange > 0 ? "text-green-600" : "text-red-500"}`}>{pick.rankChange > 0 ? "▲" : "▼"} {Math.abs(pick.rankChange)}</span>;
}

function ScoreBars({ scores }: { scores: Record<string, number> }) {
  return <div className="space-y-2">{Object.entries(scoreLabels).map(([key, label]) => <div key={key} className="grid grid-cols-[92px_1fr_34px] items-center gap-2 text-xs"><span className="text-fg-muted">{label}</span><div className="h-1.5 overflow-hidden rounded-full bg-surface-2"><div className="h-full rounded-full bg-[#1769D2]" style={{ width: `${Math.max(0, Math.min(100, scores[key] ?? 0))}%` }} /></div><strong className="text-right text-fg">{Math.round(scores[key] ?? 0)}</strong></div>)}</div>;
}

export default function DailyTopPicksDashboard() {
  const [data, setData] = useState<HomeData | null>(null);
  const [selected, setSelected] = useState<Pick | null>(null);
  const [detail, setDetail] = useState<any>(null);
  useEffect(() => { let active = true; fetch("/api/dashboard/home", { cache: "no-store" }).then((r) => r.json()).then((value) => { if (active) setData(value); }).catch(() => { if (active) setData({ ready: false, date: null, marketBrief: null, topPicks: [] }); }); return () => { active = false; }; }, []);
  useEffect(() => { if (!selected) { setDetail(null); return; } let active = true; fetch(`/api/top-picks/${encodeURIComponent(selected.ticker)}`, { cache: "no-store" }).then((r) => r.ok ? r.json() : null).then((value) => { if (active) setDetail(value); }); return () => { active = false; }; }, [selected]);
  if (!data) return <section className="mb-8 rounded-md border border-border bg-surface p-6 text-sm text-fg-muted">AI Market Intelligence를 불러오는 중…</section>;
  if (!data.ready) return <section className="mb-8 rounded-md border border-dashed border-border bg-surface p-6"><p className="font-bold text-fg">AI Market Intelligence</p><p className="mt-1 text-sm text-fg-muted">마이그레이션과 일일 스코어링이 완료되면 Daily Brief와 Top Picks가 표시됩니다.</p></section>;
  const brief = data.marketBrief;
  return <section className="mb-8 space-y-4" aria-label="AI Market Intelligence">
    <div className="flex items-end justify-between"><div><div className="flex items-center gap-2"><p className="text-[11px] font-bold tracking-[0.12em] text-[#0D57BA]">DAILY AI MARKET INTELLIGENCE</p>{data.demo && <span className="rounded bg-amber-100 px-2 py-0.5 text-[10px] font-black text-amber-700">LOCAL DEMO</span>}</div><h2 className="mt-1 text-xl font-black text-fg">Daily Market Brief</h2>{data.demo && <p className="mt-1 text-[11px] text-amber-700">UI 동작 확인용 예시 데이터입니다. 실제 투자 데이터가 아닙니다.</p>}</div><span className="text-xs text-fg-muted">{data.date}</span></div>
    {brief && <div className="space-y-4"><article className="rounded-md border border-border bg-surface p-5"><p className="text-xs font-bold text-[#1769D2]">TODAY&apos;S MARKET VIEW</p><h3 className="mt-2 text-lg font-black text-fg">{brief.headline}</h3><p className="mt-2 text-sm leading-6 text-fg-muted">{brief.summary}</p><div className="mt-4 flex flex-wrap gap-2">{brief.indicators?.map((item, i) => <span key={i} className="rounded-md bg-surface-2 px-2.5 py-1 text-xs text-fg"><b>{item.label}</b> {item.value} <em className="not-italic text-fg-muted">{item.change}</em></span>)}</div>{brief.timeline && <div className="mt-5 grid gap-2 md:grid-cols-3">{[["최근 2주", brief.timeline.twoWeeks], ["최근 3일", brief.timeline.threeDays], ["오늘", brief.timeline.today]].map(([label, value], i) => <div key={label} className="relative rounded-md border border-border bg-surface-2 p-3"><span className="text-[10px] font-black text-[#1769D2]">{i + 1} · {label}</span><p className="mt-1 text-xs leading-5 text-fg-muted">{value}</p></div>)}</div>}</article><div className="grid gap-4 lg:grid-cols-[1.35fr_1fr]"><article className="rounded-md border border-border bg-surface p-4"><h3 className="text-sm font-black text-fg">Today&apos;s Key Issues</h3><div className="mt-3 grid gap-3 md:grid-cols-3">{brief.issues?.slice(0, 3).map((issue, i) => <div key={i} className="rounded-md bg-surface-2 p-3"><p className="text-xs font-black text-fg">{issue.title}</p><p className="mt-1 text-[11px] leading-4 text-fg-muted">{issue.whatChanged || issue.summary}</p>{issue.marketImpact && <p className="mt-2 text-[11px] leading-4 text-[#1769D2]"><b>시장 영향</b> · {issue.marketImpact}</p>}{issue.watchPoint && <p className="mt-1 text-[11px] leading-4 text-amber-700"><b>확인할 것</b> · {issue.watchPoint}</p>}</div>)}</div></article><article className="rounded-md border border-border bg-surface p-4"><h3 className="text-sm font-black text-fg">Today&apos;s Key Themes</h3><div className="mt-3 space-y-2">{brief.themes?.map((theme, i) => <div key={i} className="flex items-center justify-between rounded-md bg-surface-2 px-3 py-2" title={theme.reason}><div><p className="text-xs font-bold text-fg">{theme.themeKo || themeLabelKo(theme.themeCode || theme.theme || "")}</p><p className="mt-0.5 text-[10px] text-fg-muted">{theme.reason}</p></div><span className={`rounded-full px-2 py-1 text-xs font-black ${(theme.score ?? 0) >= 0 ? "bg-green-50 text-green-700" : "bg-red-50 text-red-600"}`}>{typeof theme.score === "number" ? `${theme.score > 0 ? "+" : ""}${theme.score.toFixed(1)}` : ""}</span></div>)}</div></article></div></div>}
    <div className="rounded-md border border-border bg-surface p-4 sm:p-5"><div className="mb-4 flex items-end justify-between"><div><p className="text-[11px] font-bold tracking-[0.12em] text-[#0D57BA]">DETERMINISTIC SELECTION</p><h2 className="mt-1 text-xl font-black text-fg">Today&apos;s Top Pick</h2></div><p className="text-[11px] text-fg-muted">점수·신뢰도·유동성·분산 기준 적용</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{data.topPicks.map((pick) => <button type="button" key={pick.ticker} onClick={() => setSelected(pick)} className="rounded-md border border-border bg-surface p-4 text-left transition hover:-translate-y-0.5 hover:border-[#1769D2]/40 hover:shadow-sm"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><span className="text-2xl font-black text-[#1428A0]">{pick.rank}</span><RankChange pick={pick} /></div><span className={`rounded px-2 py-1 text-[10px] font-bold ${typeTone[pick.type] ?? "bg-surface-2 text-fg-muted"}`}>{pick.type}</span></div><h3 className="mt-3 truncate text-sm font-black text-fg">{pick.company}</h3><p className="text-[11px] text-fg-muted">{pick.ticker}</p><div className="mt-3 flex items-end justify-between"><div><p className="text-[10px] text-fg-muted">SCORE</p><strong className="text-xl text-fg">{pick.score.toFixed(1)}</strong></div><div className="text-right"><p className="text-[10px] text-fg-muted">CONFIDENCE</p><strong className="text-sm text-fg">{Math.round(pick.confidence)}</strong></div></div><p className="mt-3 line-clamp-3 text-xs leading-5 text-fg-muted">{pick.summary || pick.keyReasons?.[0] || "구조화된 근거를 준비 중입니다."}</p></button>)}</div></div>
    {selected && <div className="fixed inset-0 z-50 flex justify-end bg-black/35" onMouseDown={(e) => { if (e.currentTarget === e.target) setSelected(null); }}><aside className="h-full w-full max-w-xl overflow-y-auto bg-surface p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-[#1769D2]">TOP PICK #{selected.rank}</p><h2 className="mt-1 text-2xl font-black text-fg">{selected.company}</h2><p className="text-sm text-fg-muted">{selected.ticker} · {selected.type}</p></div><button onClick={() => setSelected(null)} aria-label="닫기" className="rounded p-2 text-xl text-fg-muted hover:bg-surface-2">×</button></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-md bg-surface-2 p-4"><p className="text-xs text-fg-muted">Total Score</p><strong className="text-3xl text-fg">{selected.score.toFixed(1)}</strong></div><div className="rounded-md bg-surface-2 p-4"><p className="text-xs text-fg-muted">Confidence</p><strong className="text-3xl text-fg">{Math.round(selected.confidence)}</strong></div></div><div className="mt-6"><h3 className="mb-3 text-sm font-black text-fg">점수 기여도</h3><ScoreBars scores={selected.scores} /></div><div className="mt-6"><h3 className="text-sm font-black text-fg">선정 이유</h3><ul className="mt-2 space-y-2 text-sm leading-6 text-fg-muted">{(detail?.keyReasons ?? selected.keyReasons ?? []).map((reason: string, i: number) => <li key={i}>• {reason}</li>)}</ul></div><div className="mt-6"><h3 className="text-sm font-black text-fg">주요 리스크</h3><ul className="mt-2 space-y-2 text-sm leading-6 text-fg-muted">{(detail?.risks ?? selected.risks ?? []).map((risk: string, i: number) => <li key={i}>• {risk}</li>)}</ul></div>{detail?.history?.length > 0 && <div className="mt-6"><h3 className="text-sm font-black text-fg">최근 Score 변화</h3><div className="mt-2 flex gap-2 overflow-x-auto">{detail.history.slice().reverse().map((row: any) => <div key={row.trade_date} className="min-w-20 rounded bg-surface-2 p-2 text-center"><p className="text-[10px] text-fg-muted">{String(row.trade_date).slice(5)}</p><b className="text-sm text-fg">{Number(row.total_score).toFixed(1)}</b></div>)}</div></div>}</aside></div>}
  </section>;
}
