"use client";
import { useMemo, useState } from "react";
import type { WmExpert } from "@/lib/wmExperts";

export default function MeetingBookingModal({ expert, open, onClose, onConfirm }: { expert: WmExpert | null; open: boolean; onClose: () => void; onConfirm: (value: string) => void }) {
  const today = new Date();
  const [month, setMonth] = useState(new Date(today.getFullYear(), today.getMonth(), 1));
  const [date, setDate] = useState<Date | null>(null); const [time, setTime] = useState<string | null>(null);
  const days = useMemo(() => Array.from({ length: new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate() }, (_, i) => new Date(month.getFullYear(), month.getMonth(), i + 1)), [month]);
  const morning = ["10:00", "10:30", "11:00", "11:30"]; const afternoon = Array.from({ length: 17 }, (_, i) => `${String(12 + Math.floor(i / 2)).padStart(2, "0")}:${i % 2 ? "30" : "00"}`);
  if (!open || !expert) return null;
  const pick = (candidate: Date) => candidate >= new Date(today.getFullYear(), today.getMonth(), today.getDate());
  const label = date && time ? `${date.toLocaleDateString("sv-SE")} ${time}` : "";
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/70 p-4" onMouseDown={onClose}><div role="dialog" aria-modal="true" className="mx-auto my-6 w-full max-w-2xl rounded-2xl border border-border bg-surface p-5 shadow-2xl" onMouseDown={(e) => e.stopPropagation()}><div className="flex justify-between gap-4"><div><h2 className="text-lg font-black text-fg">미팅 예약</h2><p className="mt-1 text-xs text-fg-muted">{expert.name} 전문가와 상담 일정을 선택해 주세요.</p></div><button type="button" onClick={onClose} className="text-sm text-fg-muted">닫기</button></div><div className="mt-5 grid gap-5 md:grid-cols-2"><section><div className="mb-3 flex items-center justify-between"><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} className="rounded border border-border px-2 py-1">&lt;</button><b className="text-sm text-fg">{month.getFullYear()}.{month.getMonth() + 1}</b><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} className="rounded border border-border px-2 py-1">&gt;</button></div><div className="grid grid-cols-7 gap-1 text-center text-[10px] text-fg-muted">{"일월화수목금토".split("").map((day) => <span key={day}>{day}</span>)}{Array.from({ length: days[0].getDay() }).map((_, i) => <span key={`blank-${i}`} />)}{days.map((day) => { const active = date?.toDateString() === day.toDateString(); const isToday = day.toDateString() === today.toDateString(); const available = pick(day); return <button disabled={!available} type="button" key={day.toISOString()} onClick={() => { setDate(day); setTime(null); }} className={`h-9 rounded-md ${active ? "bg-emerald-600 text-white" : isToday ? "bg-emerald-100 text-emerald-800" : "hover:bg-surface-2"} ${!available ? "cursor-not-allowed text-slate-300" : ""}`}>{day.getDate()}{isToday && <span className="block text-[8px]">오늘</span>}</button>; })}</div></section><section><h3 className="text-sm font-bold text-fg">시간 선택</h3>{[["오전", morning], ["오후", afternoon]].map(([heading, slots]) => <div key={heading as string} className="mt-3"><p className="mb-2 text-xs font-bold text-fg-muted">{heading as string}</p><div className="grid grid-cols-4 gap-2">{(slots as string[]).map((slot) => <button disabled={!date} type="button" key={slot} onClick={() => setTime(slot)} className={`rounded-md border px-1 py-2 text-xs ${time === slot ? "border-emerald-600 bg-emerald-600 text-white" : "border-border bg-surface-2 text-fg"} disabled:opacity-40`}>{slot}</button>)}</div></div>)}</section></div><div className="mt-5 rounded-xl bg-surface-2 p-3 text-xs text-fg-muted">{label ? `${expert.name} 전문가 / ${label} 예약 요청` : "날짜와 시간을 선택해 주세요."}</div><button disabled={!date || !time} type="button" onClick={() => { onConfirm(`${expert.name} 전문가 / ${label} 예약 요청`); onClose(); }} className="mt-4 w-full rounded-xl bg-emerald-600 py-3 text-sm font-bold text-white disabled:opacity-40">예약 요청</button></div></div>;
}
