import { ASSETS, FACTORS, type AssetId, type MacroStressResponse, type MonthlyRow, type OlsModel, type RiskMetrics, type ScenarioResult, type Vector, type Weights } from "./types";
import { cholesky, covariance, inverse, mean, multiply, normal, quantile, seeded, std } from "./math";
import { loadMonthlyRows } from "./data";
export const HISTORICAL_SCENARIOS={dotcom:{label:"Dot-com bubble",start:"2000-03",end:"2002-10"},gfc:{label:"Global financial crisis",start:"2007-10",end:"2009-03"},covid:{label:"COVID-19",start:"2020-02",end:"2020-04"},inflation_2022:{label:"2022 inflation/rate shock",start:"2022-01",end:"2022-10"}} as const;
export type HistoricalScenarioId=keyof typeof HISTORICAL_SCENARIOS;
function normalCdf(x:number){const t=1/(1+.2316419*Math.abs(x)),d=.3989423*Math.exp(-x*x/2),p=1-d*t*(.3193815+t*(-.3565638+t*(1.781478+t*(-1.821256+t*1.330274))));return x>0?p:1-p;}
function fit(rows:MonthlyRow[],asset:AssetId):OlsModel {
  const usable=rows.filter(row=>Number.isFinite(row.assets[asset]));
  const x=usable.map(row=>[1,...FACTORS.map(factor=>row.factors[factor])]),y=usable.map(row=>[row.assets[asset]]),xt=x[0].map((_,i)=>x.map(row=>row[i])),xtx=multiply(xt,x);
  for(let i=1;i<xtx.length;i++)xtx[i][i]+=1e-10;
  const inv=inverse(xtx),coef=multiply(multiply(inv,xt),y).map(row=>row[0]),pred=x.map(row=>row.reduce((sum,value,i)=>sum+value*coef[i],0)),res=y.map((value,i)=>value[0]-pred[i]),yMean=mean(y.map(value=>value[0])),sse=res.reduce((sum,value)=>sum+value*value,0),sst=y.reduce((sum,value)=>sum+(value[0]-yMean)**2,0),sigma2=sse/Math.max(usable.length-coef.length,1),se=inv.map((row,i)=>Math.sqrt(Math.max(row[i]*sigma2,0))),p=coef.map((value,i)=>2*(1-normalCdf(Math.abs(value/se[i]))));
  return {asset,alpha:coef[0],betas:Object.fromEntries(FACTORS.map((factor,i)=>[factor,coef[i+1]])) as Vector,pValues:Object.fromEntries(FACTORS.map((factor,i)=>[factor,p[i+1]])) as Vector,r2:1-sse/sst,residualStd:Math.sqrt(sigma2),sampleStart:usable[0].month,sampleEnd:usable.at(-1)!.month,observations:usable.length};
}
function cumulative(values:number[]){return values.reduce((wealth,value)=>wealth*(1+value),1)-1;}
function pathMdd(values:number[]){let wealth=1,peak=1,mdd=0;for(const value of values){wealth*=1+value;peak=Math.max(peak,wealth);mdd=Math.min(mdd,wealth/peak-1);}return mdd;}
function metrics(returns:number[],mdds:number[]):RiskMetrics {const sorted=[...returns].sort((a,b)=>a-b),v95=quantile(sorted,.05),v99=quantile(sorted,.01);return {meanReturn:mean(returns),volatility:std(returns),worstReturn:sorted[0]??0,var95:v95,cvar95:mean(sorted.filter(value=>value<=v95)),var99:v99,cvar99:mean(sorted.filter(value=>value<=v99)),lossProbability:returns.filter(value=>value<0).length/returns.length,meanMdd:mean(mdds),worstMdd:[...mdds].sort((a,b)=>a-b)[0]??0,mdd95:quantile(mdds,.05)};}
function histogram(values:number[],bins=28){const low=quantile(values,.01),high=quantile(values,.99),width=(high-low)/bins||1;const result=Array.from({length:bins},(_,index)=>({mid:low+(index+.5)*width,count:0}));for(const value of values){const index=Math.max(0,Math.min(bins-1,Math.floor((value-low)/width)));result[index].count+=1;}return result;}
function historicalCenter(window:MonthlyRow[]):Vector {return {d_fed:window.reduce((sum,row)=>sum+row.factors.d_fed,0),d_ust:window.reduce((sum,row)=>sum+row.factors.d_ust,0),ret_krw:cumulative(window.map(row=>row.factors.ret_krw)),infl:mean(window.map(row=>row.factors.infl)),ret_cmd:cumulative(window.map(row=>row.factors.ret_cmd)),d_vix:window.reduce((sum,row)=>sum+row.factors.d_vix,0)};}
function monthlyCenter(center:Vector,months:number){return FACTORS.map(id=>id==="infl"?center[id]:id==="ret_krw"||id==="ret_cmd"?Math.pow(Math.max(1+center[id],.01),1/months)-1:center[id]/months);}
function simulate(center:Vector,months:number,cov:number[][],models:OlsModel[],weights:Weights,count:number,seed:number){
  const rng=seeded(seed),lower=cholesky(cov),centerMonthly=monthlyCenter(center,months),assetPaths=new Float64Array(count*months*3),returns:number[]=[],mdds:number[]=[];
  for(let scenario=0;scenario<count;scenario++){const path:number[]=[];for(let month=0;month<months;month++){const z=FACTORS.map(()=>normal(rng)),noise=lower.map((row,i)=>row.slice(0,i+1).reduce((sum,value,j)=>sum+value*z[j],0)),factors=FACTORS.map((_,i)=>centerMonthly[i]+noise[i]),assetReturns=ASSETS.map((_,assetIndex)=>models[assetIndex].alpha+factors.reduce((sum,value,i)=>sum+value*models[assetIndex].betas[FACTORS[i]],0)+normal(rng)*models[assetIndex].residualStd) as [number,number,number],offset=(scenario*months+month)*3;assetPaths[offset]=assetReturns[0];assetPaths[offset+1]=assetReturns[1];assetPaths[offset+2]=assetReturns[2];path.push(assetReturns[0]*weights.sp500+assetReturns[1]*weights.kospi+assetReturns[2]*weights.treasury);}returns.push(cumulative(path));mdds.push(pathMdd(path));}
  return {returns,mdds,metrics:metrics(returns,mdds),assetPaths};
}
function evaluateWeights(flat:Float64Array,months:number,count:number,weights:Weights){const returns:number[]=[],mdds:number[]=[];for(let scenario=0;scenario<count;scenario++){let wealth=1,peak=1,mdd=0;for(let month=0;month<months;month++){const offset=(scenario*months+month)*3,value=flat[offset]*weights.sp500+flat[offset+1]*weights.kospi+flat[offset+2]*weights.treasury;wealth*=1+value;peak=Math.max(peak,wealth);mdd=Math.min(mdd,wealth/peak-1);}returns.push(wealth-1);mdds.push(mdd);}return metrics(returns,mdds);}
function rebalance(flat:Float64Array,months:number,count:number,current:Weights,base:RiskMetrics){const sample=Math.min(count,1_000);let selected=current,best=base.cvar95+.3*base.meanMdd;for(let us=0;us<=1.0001;us+=.05)for(let kr=0;kr<=1-us+.0001;kr+=.05){const candidate={sp500:+us.toFixed(2),kospi:+kr.toFixed(2),treasury:+(1-us-kr).toFixed(2)};if(ASSETS.some(asset=>Math.abs(candidate[asset]-current[asset])>.2001))continue;const result=evaluateWeights(flat,months,sample,candidate),turnover=ASSETS.reduce((sum,asset)=>sum+Math.abs(candidate[asset]-current[asset]),0),score=result.cvar95+.3*result.meanMdd-.02*turnover;if(score>best){best=score;selected=candidate;}}return {weights:selected,metrics:evaluateWeights(flat,months,count,selected)};}
export async function runMacroStress(weights:Weights,scenarioId:HistoricalScenarioId|"custom",customCenter?:Vector,simulations=50_000):Promise<MacroStressResponse> {
  const loaded=await loadMonthlyRows(),rows=loaded.rows.filter(row=>row.month>="1990-01"),models=ASSETS.map(asset=>fit(rows,asset)),cov=covariance(rows.map(row=>FACTORS.map(factor=>row.factors[factor])));
  const definition=scenarioId==="custom"?null:HISTORICAL_SCENARIOS[scenarioId],window=definition?rows.filter(row=>row.month>=definition.start&&row.month<=definition.end&&ASSETS.every(asset=>Number.isFinite(row.assets[asset]))):[],months=definition?window.length:12;
  if(definition&&!window.length)throw new Error("No observations for historical scenario "+scenarioId);
  const center=definition?historicalCenter(window):customCenter!;
  if(!center)throw new Error("Custom scenario requires all six factor shocks.");
  const actualPath=window.map(row=>ASSETS.reduce((sum,asset)=>sum+row.assets[asset]*weights[asset],0)),predictedPath=window.map(row=>ASSETS.reduce((sum,asset,assetIndex)=>sum+weights[asset]*(models[assetIndex].alpha+FACTORS.reduce((value,factor)=>value+row.factors[factor]*models[assetIndex].betas[factor],0)),0)),simulation=simulate(center,months,cov,models,weights,simulations,42+(scenarioId==="custom"?99:Object.keys(HISTORICAL_SCENARIOS).indexOf(scenarioId))),proposal=rebalance(simulation.assetPaths,months,simulations,weights,simulation.metrics),changes=ASSETS.map(asset=>({asset,delta:proposal.weights[asset]-weights[asset]})).sort((a,b)=>a.delta-b.delta);
  const scenario:ScenarioResult={id:scenarioId,label:definition?.label??"User-defined scenario",period:definition?definition.start+" ~ "+definition.end:"12 months",months,dataStatus:definition?"actual":"custom",center,actualReturn:definition?cumulative(actualPath):null,actualMdd:definition?pathMdd(actualPath):null,actualAssetMdd:definition?Object.fromEntries(ASSETS.map(asset=>[asset,pathMdd(window.map(row=>row.assets[asset]))])) as Record<AssetId,number>:null,predictedReturn:definition?cumulative(predictedPath):null,metrics:simulation.metrics,proposedWeights:proposal.weights,proposedMetrics:proposal.metrics,rationale:"Reduce "+changes[0].asset+" by "+Math.abs(changes[0].delta*100).toFixed(1)+"%p and add "+changes[2].asset+" by "+Math.max(0,changes[2].delta*100).toFixed(1)+"%p.",histogram:histogram(simulation.returns),worst50:simulation.returns.map((value,index)=>({return:value,mdd:simulation.mdds[index]})).sort((a,b)=>a.return-b.return).slice(0,50)};
  return {generatedAt:new Date().toISOString(),sample:{requestedStart:"1990-01",actualStart:rows[0].month,actualEnd:rows.at(-1)!.month,months:rows.length},models,scenario,warnings:loaded.warnings,sources:loaded.sources};
}
